# Generated by Django 3.2.8 on 2021-11-07 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('image', models.CharField(default='https://images.unsplash.com/photo-1511367461989-f85a21fda167?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&w=1000&q=80', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=20000)),
                ('image', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 11, 7, 20, 25, 58, 53647, tzinfo=utc))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.users')),
            ],
        ),
    ]
