# Generated by Django 3.2.8 on 2021-11-10 17:24

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211110_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 10, 17, 24, 35, 408536, tzinfo=utc)),
        ),
    ]
